config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    password:      'users/password',
  }
    devise_scope :user do
      get 'addresses', to: 'users/registrations#new_address'
      post 'addresses', to: 'users/registrations#create_address'
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

  root to: 'items#index'



  resources :images do
    member do
      get 'show_image'
    end
   
  end


  resources :users, only: [:show]
  
  resources :items, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    
    collection do
      get 'search'
    end
    
    resources :purchases do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end  
  
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
  resources :images do
    member do
      get 'show_image'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :cards
  has_many :addresses, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :cards, dependent: :destroy
  
  validates :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :phone_number, :year_birth_at, :month_birth_at, :day_birth_at, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.addresses.build
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.addresses.build(@address.attributes)
    @user.save
    sign_in(:user, @user)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  def address_params
    params.require(:address).permit(:zip, :pref, :city, :block, :building, :dst_first_name, :dst_last_name, :dst_first_name_kana, :dst_last_name_kana, :user_id)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    destroy_user_session_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update, :destroy]


  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @last_name = current_user.last_name 
    @first_name = current_user.first_name
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.edit
  .edit__content
    .edit__content__header
      .edit__content__header__text
        = image_tag src="logo.png", size:'200x70'
    .edit__content__main
      .edit__content__main__childrens
      %form
        .edit__content__main__childrens__imges
          %h1 商品の編集
        = form_with(model: @item, local: true) do|f|
          .edit__content__main__childrens__imges__box
            %ul
              %li
                %h3 出品画像
              %li
            %br/
            最大１０枚まで追加可能
          = f.fields_for :item_images  do |image|
            -# .edit__content__main__childrens__imges__box__dropzone
            -# #preview

            .edit__content__main__childrens__imges__box__input
              =image.label :image, for: "upload-image" do
                .item__img__dropzone__input__input-area
                  = image.file_field :image, id:"upload-image", class: "upload-image"
                .item__img__dropzone__input__description
                  .item__img__dropzone__input__description__text
                    クリックしてファイルをアップロード
            .edit__content__main__childrens__imges__box__dropzone2
              #preview2

              .edit__content__main__childrens__imges__box__input2
                = image.label :image, for: "upload-image" do
                  .edit__content__main__childrens__imges__box__input2__inputarea
                    =image.file_field :image_url, id: "upload-image", class: "upload-image",'data-image': 0
                    .edit__content__main__childrens__imges__box__input2__inputarea__description
                      .edit__content__main__childrens__imges__box__input2__inputarea__description__text
                        クリックしてファイルをアップォード

        .new__content__main__childrens__items
          .new__content__main__childrens__items__box
            .new__content__main__childrens__items__box__box1
              %p.item__text
              商品名 
              %span
                必須
              %br/
              %input#item{name:  "item", placeholder: "40文字まで", type: "text",class:"item"}/
              %br/
              %br/
            .new__content__main__childrens__items__box__box2
              %p.item__text
                商品の説明
                %span
                  必須
              %textarea{class:"textarea",placeholder:"説明を入力してください"}
        .new__content__main__childrens__categories
          .new__content__main__childrens__categories__box
            .new__content__main__childrens__categories__box__box1
              商品の詳細
            .new__content__main__childrens__categories__box__box2
              カテゴリー 必須
              %br/
              %select#categorie{name: "categories",class:"categorie"}        
                %option{value:  "categorie1"} レーディス
                %option{value: "categorie2"} メンズ
                %option{value: "categorie3"} 日用品
                %option{value: "categorie4"} インテリア
                %option{value: "categorie5"} その他
              %br/

              %select#categorie{name: "categories_1",class:"categorie_1"}        
                %option{value: "categorie_11"} トップス
                %option{value: "categorie_22"} ジャケットアウター
                %option{value: "categorie_33"} パンツ
                %option{value: "categorie_44"} スカート
                %option{value: "categorie_55"} ワンピース
              %br/

              %select#categorie_2{name:  "categories_2",class:"categorie_2"}        
                %option{value: "categorie_11"} tシャツ
                %option{value: "categorie_22"} ブラウス
                %option{value: "categorie_33"} キャミソール
                %option{value: "categorie_44"} タンクトップ
                %option{value:"categorie_55"} その他
              %br/
            .new__content__main__childrens__categories__box__box3
              ブランド
              %br/
              %input#brnd{name: "brnd", placeholder:"", type: "text",class:"brnd"}/
            .new__content__main__childrens__categories__box__box4
              商品の状態 必須
              %br/
              %select#condition{name: "condition",class:"condition"}        
                %option{value:"condition1"} 新品、未使用
                %option{value: "condition2"} 未使用に近い
                %option{value: "condition3"} 目立った傷や汚れがあり
                %option{value: "condition4"} やや傷や汚れがあり
                %option{value: "condition5"} その他


        .new__content__main__childrens__deliverys
          .new__content__main__childrens__deliverys__box
            .new__content__main__childrens__deliverys__box__box1
              配送について
            .new__content__main__childrens__deliverys__box__box2
              配送料の負担 必須
              %br/
              %select#contribution{name: "contribution",class:"contribution"}        
                %option{value: "contribution1"} 選択してください
                %option{value: "contribution2"} 送料込み
                %option{value: "contribution3"} 着払い
               
            .new__content__main__childrens__deliverys__box__box5
              発送までの日数 必須
              %select#date{name: "date",class:"date"}        
                %option{value: "condition1"} 未定
                %option{value: "condition2"} ラクラクフリマ便
                %option{value: "condition3"} ゆうメール
                %option{value: "condition4"} レターパック
            .new__content__main__childrens__deliverys__box__box3
              配送の方法
              %br/
              %select#delivery{name: "delivery",class:"delivery"}        
                %option{value: "delivery1"} 北海道
                %option{value: "delivery2"} 神奈川
                %option{value:"delivery3"} 東京
                %option{value: "delivery4"} 福岡
            .new__content__main__childrens__deliverys__box__box4
              配送の地域 必須
              %br/
              %select#area{name: "area",class:"area"}        
                %option{value: "condition1"} 選択してください
                %option{value: "condition2"} 1~2日で発送
                %option{value: "condition3"} ２~３日で発送
                %option{value:  "condition4"} ４~７日で発送
                %option{value: "condition5"} その他
            
        .new__content__main__childrens__sale
          .new__content__main__childrens__sale__box
            価格 (¥300~9,999,999)
            .new__content__main__childrens__sale__box__box1
              .flex
                %p.left
                  販売価格 必須
                %p.rigth
                  ¥
                
              %input#price{name: "price", placeholder: "", type: "number",class:"price"}/
              
            .new__content__main__childrens__sale__box__box2
              %p.left
                販売手数料 (10%)
              %p.rigth
                ー
            .new__content__main__childrens__sale__box__box3
              .new__content__main__childrens__sale__box__box3__top
                %p.left
                  販売利益
                %p.rigth
                  ー
              .new__content__main__childrens__sale__box__box3__middle
                .new__content__main__childrens__sale__box__box3__middle__buttn1
                  %button{name: "delete", type: "button",class:"submit"} 商品削除
                .new__content__main__childrens__sale__box__box3__middle__buttn2 
                  = link_to("変更完了","#" ,class: "back") 
              .new__content__main__childrens__sale__box__box3__bottom
                %p
                  禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。



    .new__content__footer
      .new__content__footer__list
        %ul
          %li
            プライバシーポリシー
          %li
            メルカリ利用規約
          %li
            特定商取引に関する表記

      .new__content__footer__image
        .new__content__footer__image__box
          = image_tag src="logo.png", size:'120x40' 
      .new__content__footer__text
        .new__content__footer__text__box
          @Fulima,inc.

app/views/users/show.html.haml
%html  
  %body
    = render'layouts/header'

    -# .pcHeader__headerInner__nav
    -#   %ul.pcHeader__headerInner__nav__listsRight
    -#   - if user_signed_in?
    -#     %li.pcHeader__headerInner__nav__listsRight__login
    -#       =link_to"ログアウト",destroy_user_session_path
    -#   - else
    -#     %li.pcHeader__headerInner__nav__listsRight__login
    -#       =link_to"ログイン",new_user_session_path
    -#     %li.pcHeader__headerInner__nav__listsRight__new
    -#       =link_to"新規登録",new_user_registration_path
    .user-main
      %table
        %tbody
          %tr
            %th 名前
            %td 
              =@last_name
              =@first_name
          %tr
            %th ニックネーム
            %td
              =@nickname
          %tr
            %th メールアドレス
            %td
              =link_to"メールアドレス変更"
          %tr
            %th パスワード
            %td
              =link_to"パスワード変更"

          %tr
            %th クレジットカード情報
            %td
              =link_to"クレジットカード情報変更",cards_path
              #br
              =link_to"クレジットカード新規登録",new_card_path


    .appBanner
      .appBanner__inner
        %h2.appBanner__inner__title
          誰でも簡単、人生を変えるフリマアプリ
        %p.appBanner__inner__text
          今すぐ無料ダウンロード
        .appBanner__inner__icon

= render"layouts/footer"