config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    password:      'users/password',
  }
    devise_scope :user do
      get 'addresses', to: 'users/registrations#new_address'
      post 'addresses', to: 'users/registrations#create_address'
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

  root to: 'items#index'



  resources :images do
    member do
      get 'show_image'
    end
   
  end


  resources :users, only: [:show]
  
  resources :items, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    
    collection do
      get 'search'
    end
    
    resources :purchases do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end  
  
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
  resources :images do
    member do
      get 'show_image'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
extend ActiveHash::Associations::ActiveRecordExtensions
belongs_to_active_hash :prefecture
has_many :images, dependent: :destroy
belongs_to :category, optional: true
belongs_to :user

accepts_nested_attributes_for :images,allow_destroy: true



validates :images, presence: true,length: {minmum: 1, maximum: 10}

validates :name,:price,:explain,:postage,:region,:category_id,:condition,:shipping, presence: true
validates :name, length: { maximum: 40 }
validates :name,length: {  maximum: 1000 }
validates :price, presence: true, inclusion: 300..9999999


def self.search(search)
  return Item.all unless search
  Item.where('name LIKE(?)', "%#{search}%")
end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_items, only: [:show,:edit,:update,:destroy]
  

  def index
    @items = Item.includes(:images).order("created_at DESC").limit(10)
    @parents = Category.all.order("id ASC").limit(13)
  end

  def show
    @parents = Category.where(ancestry:nil)
  end

  def new
    if user_signed_in?
      @item = Item.new
      @item.images.new
    else
      redirect_to new_user_registration_path
    end
    @prefectures=Prefecture.all
    #セレクトボックスの初期値設定
    # @category_parent_array = ["選択してください"]
    #データベースから、親カテゴリーのみ抽出し、配列化

    Category.where(ancestry: nil).each do |parent|
      @category_parent_array = Category.roots.pluck(:name)
    end
  end


  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end


  def create
    @prefectures=Prefecture.all
    @item = Item.new(item_params)
    if @item.category_id != 0
      @item.save
    else
      render new_item_path
    end
  end

  def edit
    if current_user.id == @item.user_id
      @image = @item.images
      @prefectures=Prefecture.all
      @items = Category.where(ancestry:nil)
      @category_parent_array = ["選択してください"]
      @category_children_array = ["選択してください"]
      @category_grandchildren_array = ["選択してください"]
      #データベースから、親カテゴリーのみ抽出し、配列化
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
        @category_children_array << parent.name
        @category_grandchildren_array << parent.name
        @parents = Category.all.order("id ASC").limit(13)
        end
    else
      redirect_to root_path
    end
  end
  

  def update
    @image = @item.images
    @item.user_id == current_user.id
    if @item.update(item_params)
      redirect_to items_path
    else
      flash[:alert] = '編集に失敗しました。必須項目を確認してください。'
      render 'edit'
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def search
    @items = Item.search(params[:keyword])
  end


  private
  def item_params
    params.require(:item).permit(:name, :price,:explain,:postage,:region,:condition,:category_id,:shipping,:brand,:size,images_attributes: [:image,:_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_items
    @item = Item.find(params[:id])
  end

end



#     # @parents = Category.all.order("id ASC").limit(13)
#     @selected_grandchild_category = @item.category.name
#     @category_grandchildren_array = [{id: "---", name: "---"}]
#     Category.find("#{@selected_grandchild_category.name}").siblings.each do |grandchild|
#       grandchildren_hash = {id: "#{grandchild.id}", name: "#{grandchild.name}"}
#       @category_grandchildren_array << grandchildren_hash
#   end
#   @selected_child_category = @selected_grandchild_category.parent

#   @category_children_array = [{id: "---", name: "---"}]
#     Category.find("#{@selected_child_category.id}").siblings.each do |child|
#       children_hash = {id: "#{child.id}", name: "#{child.name}"}
#       @category_children_array << children_hash
#   end
#   @selected_parent_category = @selected_child_category.parent

#   @category_parents_array = [{id: "---", name: "---"}]
#   Category.find("#{@selected_parent_category.id}").siblings.each do |parent|
#       parent_hash = {id: "#{parent.id}", name: "#{parent.name}"}
#       @category_parents_array << parent_hash
# end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/create.html.haml
.pcHeader
  .pcHeader__headerInner
    .pcHeader__headerInner__mainHeader
      %h1.pcHeader__headerInner__mainHeader__icon
        = link_to image_tag(src="logo.png",size:"140x41"),root_path

.body
  %h2 出品完了！
  %br/
  %h2 FURIMAをお楽しみください


.new__content__footer
  .new__content__footer__list
    %ul
      %li
        %br/
        =link_to "FURIMA トップへ戻る", root_path
      %li
        %br/
        =link_to "続けて出品する", new_item_path
      %li
        %br/
        =link_to "マイページ", user_path(current_user)

app/views/items/edit.html.haml
.edit
  .edit__content
    .edit__content__header
      .edit__content__header__text
        = link_to image_tag(src="logo.png",size:"140x41"),root_path


    .edit__content__main
      .edit__content__main__childrens
      = form_with(model: @item, local: true)do |f|
        .edit__content__main__childrens__imges
          .edit__content__main__childrens__imges__box
            商品画像
            %span.form-require 必須
            #image-box


              #previews
                -if @item.persisted?
                  - @image.each_with_index do |image, i|
                    .preview{data:{index:i}}
                      =image_tag image.image.url,data:{index:i}, class: "js-file_group" ,width:"100px",height:'100px'
                    
                      %a{ class: "js-remove" }削除
                      
                      %a{ class: "abc"}

              #form-wrapper
                %label.icons
                  = icon( 'fas',"fas fa-camera", class: "icon")
                  %p.text
                    アルバムから画像を選択
                    %br/
                    【最大10枚までアップロード可能】
                    %br/
                    %br/
                    ファイル形式：JPEG,PNG,GIF
                    
                = f.fields_for :images do |image|
                  .js-file_group{"data-index" => "#{image.index}"}
                    = image.file_field :image,type: "file" ,class:"abc",value:"textarea"

                    - if @item.persisted?
                      =image.check_box :_destroy,data:{index:image.index},class:"hidden-destroy"
                  - if @item.persisted?
                    .js-file_group{"data-index"=>"#{@item.images.count}"}
                      = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]", class: 'abc'
                      .js-remove

        .edit__content__main__childrens__items
          .edit__content__main__childrens__items__box
            .edit__content__main__childrens__items__box__box1
              %p.item__text
              商品名 
              %span.form-require 必須
              %br/

              = f.text_field  :name,  placeholder: "40文字まで", type: "text"

                
              %br/
              %br/
              -# %p.item__text-color
              -# 入力してください
            .edit__content__main__childrens__items__box__box2
              %p.item__text
                商品の説明

                %span.form-require
                  必須
              = f.text_area :explain,class:"textarea"

              %br/
              %br/
              -# 入力してください

        .edit__content__main__childrens__categories
          .edit__content__main__childrens__categories__box
            .edit__content__main__childrens__categories__box__box1
              商品の詳細

            .edit__content__main__childrens__categories__box__box2

              .listing-product-detail__category
                = f.label 'カテゴリー', class: 'category-label'
                %span.form-require 必須
                .listing-select-wrapper__box
                  =@item.category.parent.parent.name
                  =@item.category.parent.name
                  =@item.category.name
                .listing-select-wrapper__box
                  = f.select :category, Category.roots.pluck(:name), {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}

            .edit__content__main__childrens__categories__box__box5
              サイズ
              %br/
              = f.text_field  :size,name: "size", placeholder:"", type: "text",class:"size"

            .edit__content__main__childrens__categories__box__box3
              ブランド
              %br/
              = f.text_field  :brand,name: "brnd", placeholder:"", type: "text",class:"brnd"
              
            .edit__content__main__childrens__categories__box__box4
              商品の状態
              %span.form-require 必須
              %br/
              = f.select(:condition, [["新品、未使用", "新品、未使用"], ["未使用に近い", "未使用に近い"],["目立った傷や汚れがあり","目立った傷や汚れがあり"],["やや傷や汚れがあり","やや傷や汚れがあり"],["その他","その他"]], {prompt:"選択してください"}, {class: "condition"})
              

        .edit__content__main__childrens__deliverys
          .edit__content__main__childrens__deliverys__box
            .edit__content__main__childrens__deliverys__box__box1
              配送について
            .edit__content__main__childrens__deliverys__box__box2
              配送料の負担 
              %span.form-require 必須
              %br/

              = f.select(:postage, [["送料込み", "送料込み"], ["着払い", "着払い"]], {prompt:"選択してください"}, {class: "postage"})

            .edit__content__main__childrens__deliverys__box__box3
              配送の日数
              %span.form-require 必須
              %br/
              = f.select(:shipping, [["１〜２日で発送", "１〜２日で発送"], ["2〜3日で発送", "2〜3日で発送"],["4〜7日で発送","4〜7日で発送"]] ,{prompt:"選択してください"}, {class: "delivery"})
            .edit__content__main__childrens__deliverys__box__box4
              配送の地域 
              %span.form-require 必須
              -# 必須
              %br/
              = f.select :region, options_for_select(Prefecture.all.map{|c|[c[:name], c[:name]]}), {prompt:"選択してください"}, {class: "area"} 
            
        .edit__content__main__childrens__sale
          .edit__content__main__childrens__sale__box
            出品価格
            %span.form-require 必須
            %span.form-require3 半角
            .edit__content__main__childrens__sale__box__box1
              .flex
                %p.left
                  -# 販売価格
                  ¥300-¥9,999,999 の範囲で
                  %br/
                  入力してください
                %p.rigth
                  ¥

                
              
              =f.number_field :price, placeholder: "", type: "number",class:"price"
              
            .edit__content__main__childrens__sale__box__box2
            .edit__content__main__childrens__sale__box__box3
              .edit__content__main__childrens__sale__box__box3__top
                
              .edit__content__main__childrens__sale__box__box3__middle
                .edit__content__main__childrens__sale__box__box3__middle__buttn1
                  =f.submit name: "submit", class:"submit", value: "更新"
                .edit__content__main__childrens__sale__box__box3__middle__buttn2 
                  = link_to "商品削除", item_path(@item),method: :delete ,class: "back" 
              .edit__content__main__childrens__sale__box__box3__bottom
                %p
                %br/
                %br/
                禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。


    .edit__content__footer
      .edit__content__footer__list
        %ul
          %li
            プライバシーポリシー
          %li
            FURIMA利用規約
          %li
            特定商取引に関する表記

      .edit__content__footer__image
        .edit__content__footer__image__box
          =link_to image_tag(src="logo.png", size:'140x41'),root_path

      

app/views/items/index.html.haml
= render'layouts/header'
.main
  %section.mainVisual
    .content
      %h2.content__subtitle 人生を変えるフリマアプリ
      %p.content__text FURIMAはだれでもかんたんに出品・購入できる
      %p.content__text フリマアプリです
      .btn
        = link_to 'https://www.apple.com/jp/ios/app-store/', class: "productLink" do
          .btn__aBtn
        = link_to 'https://play.google.com/', class: "productLink" do
          .btn__gBtn

  %section.topIntroduction
    %h2.subtitle フリマが選ばれる３つの理由
    %ul.lists
      %li.list
        .list__pct
          %span.number 1
          = image_tag "pict-reason-01.jpg", alt: "写真", class: "image"
        %h3.list__text 
          %span.strong ３分 
          ですぐに出品
        %p.list__description スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pct
          %span.number 2
          = image_tag "pict-reason-02.jpg", alt: "写真", class: "image"
        %h3.list__text 
          %span.strong シンプル
          で使いやすい
        %p.list__description めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list--last
        .list__pct
          %span.number 3
          = image_tag "pict-reason-03.jpg", alt: "写真", class: "image"
        %h3.list__text
          手数料 
          %span.strong 業界最安
        %p.list__description 最大3%でお得に出品&購入！
      
  %section.topMiddleDl
    .topMiddleDl__inner
      %h2.subtitle2 会員数日本第一位 
      %p FURIMAは、フリマアプリで最も人気。
      %p 出品・購入回数も業界最多です！
      %p ほしかったあの商品に出会えるかもしれません。
      .btn
        = link_to 'https://www.apple.com/jp/ios/app-store/', class: "productLink" do
          .btn__aBtn
        = link_to 'https://play.google.com/', class: "productLink" do
          .btn__gBtn

  %section.topKeyFeatur
    %h2.head FURIMAの特徴
    .items
      .item
        %figure.item__img
          = image_tag "icon-01.png", alt: "写真", class: "icon"
        %h3.item__subtitle 簡単に売り買いできる
        %p.item__detail スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .item
        %figure.item__img
          = image_tag "icon-03.png", alt: "写真", class: "icon"
        %h3.item__subtitle 売上金は即日振込みに対応
        %p.item__detail 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .item
        %figure.item__img
          = image_tag "icon-04.png", alt: "写真", class: "icon"
        %h3.item__subtitle 様々な支払いに対応
        %p.item__detail お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

  %section.pickupContainer
    %h2.head いろいろなアイテムが続々出品！
    .productBox
      .productHead
        = link_to '/', class: "productLink" do 
          %h3.title New Coming
      .productLists
        - @items.each do |item|

          - if item.buyer_id.blank?
            = link_to "/items/#{item.id}", class: "productLink" do
              .productList
                %figure.productList__img
                  = image_tag item.images[0].image.url, size: '200x200' if item.images[0]
                .productList__body
                  .details
                    = item.name
                  %p
                    = "#{item.price}円"
                  %p (税込)
          - else
            .productList
              %figure.productList__img
                = image_tag item.images[0].image.url, size: '200x200' if item.images[0]
              %p.productList__soldout SoldOut

              .productList__body
                .details
                  = item.name
                %p
                  = "#{item.price}円"
                %p (税込)

.appBanner
  .inner
    %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
    %p.innner__text 今すぐ無料ダウンロード！
    .btn-b
      = link_to 'https://www.apple.com/jp/ios/app-store/', class: "productLink" do
        .btn-b__aBtn
      = link_to 'https://play.google.com/', class: "productLink" do
        .btn-b__gBtn
= render'layouts/footer'

app/views/items/new.html.haml
.new
  .new__content
    .new__content__header
      .new__content__header__text
        = link_to image_tag(src="logo.png",size:"140x41"),root_path


    .new__content__main
      .new__content__main__childrens
      = form_with(model: @item, local: true)do |f|
        .new__content__main__childrens__imges
          .new__content__main__childrens__imges__box
            商品画像
            %span.form-require 必須
            #image-box
              #previews
                -if @item.persisted?

                  =@item.images.each_with_index do |image, i|
                    =image_tag image.src.url,data:{index:i},width:"100",height:'100'
              = f.fields_for :images do |t|
                #form-wrapper
                  %label.icons
                    = icon( 'fas',"fas fa-camera", class: "icon")
                    %p.text
                      アルバムから画像を選択
                      %br/
                      【最大10枚までアップロード可能】
                      %br/
                      %br/
                      ファイル形式：JPEG,PNG,GIF
                  .js-file_group{"data-index" => "#{t.index}"}
                    = t.file_field :image,type: "file" ,class:"abc",value:"textarea",required: true

                    - if @item.persisted?
                      =image.check_box :_destroy,data:{index:image.index},class:"hidden-destroy"
                  - if @item.persisted?
                    .js-file_group{"data-index"=>"#{@item.images.count}"}
                      = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][:image]", class: 'abc'
                      .js-remove

        .new__content__main__childrens__items
          .new__content__main__childrens__items__box
            .new__content__main__childrens__items__box__box1
              %p.item__text
              商品名 
              %span.form-require 必須
              %br/

              = f.text_field  :name,  placeholder: "40文字まで", type: "text",required: true

              %br/
              %br/

            .new__content__main__childrens__items__box__box2
              %p.item__text
              説明
              %span.form-require 必須
              = f.text_area :explain,class:"textarea",placeholder: "商品の説明（例：色、素材、定価、注意点など）を入力してください",required: true

          
        .new__content__main__childrens__categories
          .new__content__main__childrens__categories__box
            .new__content__main__childrens__categories__box__box1
              商品詳細
            
            .new__content__main__childrens__categories__box__box4
              商品の状態
              %span.form-require 必須
              %br/
              = f.select(:condition, [["新品、未使用", "新品、未使用"], ["未使用に近い", "未使用に近い"],["やや目立った傷や汚れがあり","やや目立った傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["ジャンク品","ジャンク品"]], {prompt:"選択してください"}, {class: "condition",required: true})
            
            .new__content__main__childrens__categories__box__box2
              .listing-product-detail__category
                = f.label 'カテゴリー', class: 'category-label',required: true
                %span.form-require 必須
                .listing-select-wrapper__box
                  = f.select :category, Category.roots.pluck(:name), {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category',required: true}

            .new__content__main__childrens__categories__box__box5
              サイズ
              %br/
              = f.text_field :size, placeholder:"", type: "text",class:"size"

            .new__content__main__childrens__categories__box__box3
              ブランド
              %br/
              = f.text_field  :brand, placeholder:"", type: "text",class:"brnd"

        .new__content__main__childrens__deliverys
          .new__content__main__childrens__deliverys__box
            .new__content__main__childrens__deliverys__box__box1
              配送について
            .new__content__main__childrens__deliverys__box__box2
              配送料の負担 
              %span.form-require 必須
              %br/
              = f.select(:postage, [["送料込み", "送料込み"], ["着払い", "着払い"]], {prompt:"選択してください"}, {class: "contribution",required: true})
            .new__content__main__childrens__deliverys__box__box3
              発送までの日数
              %span.form-require 必須
              %br/
              = f.select(:shipping, [["1〜2日で発送", "1〜2日で発送"], ["2〜3日で発送", "2〜3日で発送"],["4〜7日で発送","4〜7日で発送"]] ,{prompt:"選択してください"}, {class: "delivery",required: true})
            .new__content__main__childrens__deliverys__box__box4
              発送元の地域
              %span.form-require 必須
              %br/
              = f.select :region, options_for_select(@prefectures.map{|c|[c[:name], c[:name]]}), {prompt:"選択してください"}, {class: "area",required: true} 
            
        .new__content__main__childrens__sale
          .new__content__main__childrens__sale__box
            販売価格
            %span.form-require 必須
            %span.form-require3 半角
            .new__content__main__childrens__sale__box__box1
              .flex
                %p.left
                  (300〜9,999,999) 
                %p.rigth
                  ¥
              =f.number_field :price, placeholder: "", type: "number",class:"price",required: true
              
            .new__content__main__childrens__sale__box__box3__middle
              .new__content__main__childrens__sale__box__box3__middle__buttn1
                =f.submit name: "submit", class:"submit", value: "送信"
              .new__content__main__childrens__sale__box__box3__middle__buttn2 
                = link_to("戻る","/" ,class: "back") 
            .new__content__main__childrens__sale__box__box3__bottom
              %p
                禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。


    .new__content__footer
      .new__content__footer__list
        %ul
          %li
            プライバシーポリシー
          %li
            FURIMA利用規約
          %li
            特定商取引に関する表記

      .new__content__footer__image
        .new__content__footer__image__box
          =link_to image_tag(src="logo.png", size:'140x41'),root_path

app/views/items/search.html.haml
= render'layouts/header'
.search
  -if @items.length != 0

    -@items.each do |item|
      - if item.buyer_id.blank?
        .search__boxs
          .search__boxs__image
            = link_to item_path(item.id) do
              = image_tag item.images[0].image.url, size: '180x180' if item.images[0]
          .search__boxs__price
            ¥
            = item.price
            %p.text
              (税込み)
          .search__boxs__name
            = item.name
      - else
        .search__boxs
          .search__boxs__image
            = image_tag item.images[0].image.url, size: '180x180' if item.images[0]
          %span.searchlist__soldout SoldOut
          .search__boxs__price
            ¥
            = item.price
            %p.text
              (税込み)
          .search__boxs__name
            = item.name

  -elsif @items.length == 0
    .content
      検索結果はありません
  -else 
    エラーが発生しました
=render"layouts/footer_usr"

app/views/items/show.html.haml
%html
  %body
    = render'layouts/header'
    .breadCrumbs
      %ul
        %li
          =link_to"FURIMA", root_path
        %li
          = icon('fa','angle-right')
        %li
          ="商品詳細"
        %li
          = icon('fa','angle-right')
          = @item.name

    .main
      .main__showMain
        .main__showMain__contentLeftqq
        .main__showMain__contentRight
          .main__showMain__contentRight__top-content
            .main__showMain__contentRight__top-content__itemBox
              .main__showMain__contentRight__top-content__itemBox__name
                = @item.name
              .main__showMain__contentRight__top-content__itemBox__body
                %ul.main
                  %li.mainimage
                    =image_tag @item.images.first.image.url size: '200x200',class:"mainimage"
                  .subimage
                    - @item.images.each do |image|
                      %li.subimage_li
                        = image_tag image.image.url, size: '75x75',class:"subimage"

              .main__showMain__contentRight__top-content__itemBox__price
                %span
                  =@item.price
                  円
                .main__showMain__contentRight__top-content__itemBox__price__price-Detail
                  %span
                    商品説明
                    %br/
                  %p
                    = @item.explain

              .main__showMain__contentRight__top-content__itemBox__table
                
                %table
                  %tbody
                    %tr
                      %th 出品者
                      %td 
                        =@item.user.nickname
                    %tr 
                      %th カテゴリー
                      %td
                        =@item.category.parent.parent.name
                        %br
                        =@item.category.parent.name
                        %br
                        =@item.category.name
                    %tr
                      %th ブランド
                      %td
                        =@item.brand
                    %tr
                      %th 商品のサイズ
                      %td
                        =@item.size
                    %tr 
                      %th 商品の状態
                      %td 
                        =@item.condition
                    %tr
                      %th 配送料の負担
                      %td 
                        =@item.postage
                        
                    %tr
                      %th 配送元の地域
                      %td 
                        =@item.region
                        
                    %tr
                      %th 発送日の目安
                      %td 
                        =@item.shipping
                        
              -  if user_signed_in? && current_user.id == @item.user_id  
                = link_to "/items/#{params[:id]}/edit",class:"main__showMain__contentRight__top-content__itemBox__item-buy-btn" do
                  %p 編集画面に進む

                
                = link_to "商品削除", item_path(@item) ,class:"main__showMain__contentRight__top-content__itemBox__item-buy-btn",method: :delete 
                -# %a{class:"main__showMain__contentRight__top-content__itemBox__item-buy-btn",href:"/"}編集画面に進む
              -else
                = link_to "/items/#{params[:id]}/purchases/index",class:"main__showMain__contentRight__top-content__itemBox__item-buy-btn" do
                  %p 購入画面に進む

    .appBanner
      .appBanner__inner
        %h2.appBanner__inner__title
          誰でも簡単、人生を変えるフリマアプリ
        %p.appBanner__inner__text
          今すぐ無料ダウンロード
        .appBanner__inner__icon

=render"layouts/footer_usr"