config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    password:      'users/password',
  }
    devise_scope :user do
      get 'addresses', to: 'users/registrations#new_address'
      post 'addresses', to: 'users/registrations#create_address'
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

  root to: 'items#index'



  resources :images do
    member do
      get 'show_image'
    end
   
  end


  resources :users, only: [:show]
  
  resources :items, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    
    collection do
      get 'search'
    end
    
    resources :purchases do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end  
  
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
  resources :images do
    member do
      get 'show_image'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  def new
    if user_signed_in?
      card = Card.where(user_id: current_user.id)
      redirect_to action: "show" if card.exists?
    else
      redirect_to new_user_registration_path
    end
  end

  def pay #payjpとCardのデータベース作成を実施。
    # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"] #テスト環境で.envファイル呼ぶ時（本番環境対象外）
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #metadataにuser_id入れる。なくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除。
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]#テスト環境で.envファイル呼ぶ時（本番環境対象外）
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出す。
    if user_signed_in?
      card = Card.where(user_id: current_user.id).first
      if card.blank?
        redirect_to action: "new" 
      else
        # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]#テスト環境で.envファイル呼ぶ時（本番環境対象外）
        Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
        customer = Payjp::Customer.retrieve(card.customer_id)
        @default_card_information = customer.cards.retrieve(card.card_id)
      end
    else
      redirect_to new_user_registration_path
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
.card-register
  .register-area
    .register-area__box
      =link_to image_tag(src="logo.png", size:'150x50'),root_path
      %h2.card クレジットカード情報入力
      %hr
      = form_with url: pay_cards_path, method: :post, id: 'charge-form', html: {name: "inputForm"}, local: true do |form|
        %h3.card カード番号
        = form.text_field :number, class: "num", placeholder: "半角数字のみ", maxlength: "16", type: "text", id: "card_number"
        = image_tag "img_payment_01.jpg", alt: "カードロゴ", class: "card-logo"
        %br
        %h3.card 有効期限
        = form.select :exp_month, options_for_select([["--",""],["1","1"],["2","2"],["3","3"],["4","4"],["5","5"],["6","6"],["7","7"],["8","8"],["9","9"],["10","10"],["11","11"],["12","12"]])
        %span 月/
        = form.select :exp_year, options_for_select([["--",""],["19","2019"],["20","2020"],["21","2021"],["22","2022"],["23","2023"],["24","2024"],["25","2025"],["26","2026"],["27","2027"],["28","2028"],["29","2029"]])
        %span 年
        %br
        %h3.card セキュリティコード
        = form.text_field :cvc, class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        #card_token
          = form.submit "カードを登録する", id: "token_submit"

.bottom
  =render 'layouts/footer_usr'

app/views/cards/show.html.haml
.card-register
  .register-area
    .register-area__box
      = image_tag "logo.png", alt: "FURIMAロゴ", class: "furima-logo"
      %h1.card 登録クレジットカード情報
      %hr
      %br
        %p.card
          = "**** **** **** " + @default_card_information.last4
          %label.card /有効期限/
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
      = form_with url: delete_cards_path, method: :post, id: 'charge-form', html: {name: "inputForm"}, local: true do |form|
        = form.hidden_field value: "" 
        %button.delete 削除する

.new__content__footer 
  .new__content__footer__list
    %ul
      %li
        %br/
        =link_to "FURIMA トップへ戻る", root_path
      %li
        %br/
        =link_to "マイページ", user_path(current_user)
      %li
        %br/
        =link_to "登録カード情報を見る", card_path