config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    password:      'users/password',
  }
    devise_scope :user do
      get 'addresses', to: 'users/registrations#new_address'
      post 'addresses', to: 'users/registrations#create_address'
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

  root to: 'items#index'



  resources :images do
    member do
      get 'show_image'
    end
   
  end


  resources :users, only: [:show]
  
  resources :items, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    
    collection do
      get 'search'
    end
    
    resources :purchases do
      collection do
        get 'index', to: 'purchases#index'
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end  
  
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
  resources :images do
    member do
      get 'show_image'
    end
  end
end

app/views/layouts/_footer.html.haml
.footer
  %ul.footer__contents
    %li.footer__contents__content
      %h2.footer__contents__content__head
        FURIMAについて
      %ul
        %li
          =link_to"会社概要","/"
        %li
          =link_to"プライバシーポリシー","/"
        %li
          =link_to"FURIMA利用規約","/"
        %li
          =link_to"ポイントに関する特約","/"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        FURIMAをみる
      %ul
        %li
          =link_to"カテゴリー一覧","/"
        %li
          =link_to"ブランド一覧","/"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        ヘルプ&ガイド
      %ul
        %li
          =link_to"FURIMAガイド","/"
        %li
          =link_to"FURIMAロゴ利用ガイドライン","/"
        %li
          =link_to"お知らせ","/"
  .footer__logo
    %a
      = link_to image_tag(src="logo-white.png",size:"160x46.34"),root_path


  %label.purchasesBtn
    %span.purchasesBtn__text
      出品する

    %label.purchasesBtn__icon
      = link_to image_tag(src="icon_camera.png",size:"54x54"),new_item_path, class:"purchasesBtn__icon--a"

app/views/layouts/_footer_usr.html.haml
.footer
  %ul.footer__contents
    %li.footer__contents__content
      %h2.footer__contents__content__head
        -# FURIMAについて
      %ul
        %li
          =link_to"会社概要","/"
        %li
          =link_to"プライバシーポリシー","/"
        %li
          =link_to"FURIMA利用規約","/"
        %li
          =link_to"ポイントに関する特約","/"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        -# FURIMAをみる
      %ul
        %li
          =link_to"カテゴリー一覧","/"
        %li
          =link_to"ブランド一覧","/"
    %li.footer__contents__content
      %h2.footer__contents__content__head
        -# ヘルプ&ガイド
      %ul
        %li
          =link_to"FURIMAガイド","/"
        %li
          =link_to"FURIMAロゴ利用ガイドライン","/"
        %li
          =link_to"お知らせ","/"
  .footer__logo
    %a 
      = link_to image_tag(src="logo-white.png",size:"160x46.34"),root_path

app/views/layouts/_header.html.haml
.pcHeader
  .pcHeader__headerInner
    .pcHeader__headerInner__mainHeader
      %h1.pcHeader__headerInner__mainHeader__icon
      - binding.pry
        = link_to image_tag(src="logo.png",size:"140x41"),root_path
      .pcHeader__headerInner__mainHeader__searchBox
        = form_with url:  search_items_path,method: :get,local: true do |f|
          =f.text_field :keyword, placeholder: "気になる商品を見つけよう",class:"searchBox--input"
          = f.submit "検索", class: "search-btn" do
            .icon
              = image_tag src="icon-search 1.png",size:"30x30"
              -# = image_tag src="icon-search 1.png",size:"19.14x19.14", class:"a"
    .pcHeader__headerInner__nav
      %ul.pcHeader__headerInner__nav__listsLeft
        %li.pcHeader__headerInner__nav__listsLeft__item--first
          
        -# .pcHeader__headerInner__nav__listsLeft__treedisplayNone
        -#   %ul.pcHeader__headerInner__nav__listsLeft__treedisplayNone__categoryTree
        -#     %li.pcHeader__headerInner__nav__listsLeft__treedisplayNone__categoryTree__item
        -# %li.pcHeader__headerInner__nav__listsLeft__item
        -#   ブランド
          .brandsPulldowndisplayNone
      %ul.pcHeader__headerInner__nav__listsRight
      - if user_signed_in?
        %li.pcHeader__headerInner__nav__listsRight__login
          =link_to"ログアウト",destroy_user_session_path
      - else
        %li.pcHeader__headerInner__nav__listsRight__login
          =link_to"ログイン",new_user_session_path
        %li.pcHeader__headerInner__nav__listsRight__new
          =link_to"新規登録",new_user_registration_path
      - if user_signed_in?
        %li.pcHeader__headerInner__nav__listsRight__mypage
          =link_to"マイページ","/users/#{current_user.id}/"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title FreemarketSample70h
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
  %body
    = yield